//! Registering a Cloudflare WARP tunnel, so the panel can offer it as an
//! outbound with one click.
//!
//! WARP is ordinary `WireGuard` with one addition: every registration gets a
//! `client_id`, and the three bytes behind it ride in the `reserved` field of
//! each packet so Cloudflare's edge can tell registrations apart. A tunnel
//! built without them connects and then hears nothing back.
//!
//! The flow is the one every WARP client performs — there is no public API
//! contract here, only the endpoints the official app talks to:
//!
//! ```text
//! POST /v0a2158/reg          our public key  -> peer key, endpoint, addresses, client_id
//! PATCH /v0a2158/reg/{id}    warp_enabled=true (registration alone leaves it off)
//! ```
//!
//! Everything network-facing lives in [`register`]; turning a response into an
//! outbound is [`WarpRegistration::into_outbound`], which is pure and tested
//! against a captured response.

use anyhow::{Context, bail};
use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use serde::Deserialize;

use crate::models::WireguardOutbound;

/// The version string in the path travels with the client version header; the
/// two are a pair and the edge rejects a mismatch.
const API_BASE: &str = "https://api.cloudflareclient.com/v0a2158";
const CLIENT_VERSION: &str = "a-6.10-2158";
/// The official app's UA. A generic one is answered with 403.
const USER_AGENT: &str = "okhttp/3.12.1";
/// WARP's own MTU. The core would default to 1420, which fragments over the
/// tunnel and shows up as connections that open and then stall.
const WARP_MTU: i32 = 1280;

/// What the panel keeps of a registration: enough to build the outbound and
/// nothing else. The account id and token Cloudflare hands back are the keys
/// to that registration — they are used to enable WARP during [`register`] and
/// then dropped, because a panel that never calls the API again has no reason
/// to hold someone else's credentials at rest.
#[derive(Debug, Clone)]
pub struct WarpRegistration {
    pub secret_key: String,
    pub peer_public_key: String,
    pub endpoint: String,
    pub addresses: Vec<String>,
    pub reserved: Vec<u8>,
}

impl WarpRegistration {
    /// The outbound this registration describes.
    pub fn into_outbound(self) -> WireguardOutbound {
        WireguardOutbound {
            secret_key: self.secret_key,
            address: self.addresses,
            peer_public_key: self.peer_public_key,
            endpoint: self.endpoint,
            reserved: self.reserved,
            mtu: WARP_MTU,
            // WARP's edge does not need one, and a keepalive on an idle tunnel
            // is traffic the operator did not ask for.
            keep_alive: 0,
            warp: true,
        }
    }
}

// ---------------------------------------------------------------------------
// Wire shapes — only the fields we read.
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct RegResponse {
    id: String,
    token: String,
    config: RegConfig,
}

#[derive(Debug, Deserialize)]
struct RegConfig {
    client_id: String,
    peers: Vec<RegPeer>,
    interface: RegInterface,
}

#[derive(Debug, Deserialize)]
struct RegPeer {
    public_key: String,
    endpoint: RegEndpoint,
}

#[derive(Debug, Deserialize)]
struct RegEndpoint {
    /// `engage.cloudflareclient.com:2408` — a name, so the edge can move.
    host: Option<String>,
    v4: Option<String>,
}

#[derive(Debug, Deserialize)]
struct RegInterface {
    addresses: RegAddresses,
}

#[derive(Debug, Deserialize)]
struct RegAddresses {
    v4: Option<String>,
    v6: Option<String>,
}

/// A license Cloudflare refused. Separate from every other failure because it
/// is the operator's typo, not the panel's problem — the API answers it with a
/// message worth repeating verbatim ("Invalid license").
#[derive(Debug)]
pub struct BadLicense(pub String);

impl std::fmt::Display for BadLicense {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for BadLicense {}

/// Register a fresh WARP tunnel and return everything needed to dial it.
///
/// `secret_key`/`public_key` are ours — generated by the caller so the private
/// half never leaves the panel. A non-empty `license` upgrades the fresh
/// account to WARP+ before the tunnel is handed back; an invalid one fails the
/// whole call rather than quietly returning a free tunnel the operator did not
/// ask for.
pub async fn register(
    secret_key: String,
    public_key: &str,
    license: &str,
) -> anyhow::Result<WarpRegistration> {
    let http = reqwest::Client::builder()
        .user_agent(USER_AGENT)
        // Registration is two small round trips; a stuck one must not hold the
        // request handler open.
        .timeout(std::time::Duration::from_secs(20))
        .build()
        .context("build http client")?;

    let body = serde_json::json!({
        "key": public_key,
        "install_id": "",
        "fcm_token": "",
        "tos": chrono::Utc::now().to_rfc3339(),
        "model": "PC",
        "serial_number": "",
        "locale": "en_US",
    });

    let resp = http
        .post(format!("{API_BASE}/reg"))
        .header("CF-Client-Version", CLIENT_VERSION)
        .json(&body)
        .send()
        .await
        .context("cloudflare registration request")?;
    let status = resp.status();
    let text = resp.text().await.unwrap_or_default();
    if !status.is_success() {
        bail!("cloudflare answered {status}: {}", text.trim());
    }
    let reg: RegResponse =
        serde_json::from_str(&text).context("cloudflare registration response")?;

    // Registration creates the account with WARP off; without this the tunnel
    // comes up and carries nothing.
    let patch = http
        .patch(format!("{API_BASE}/reg/{}", reg.id))
        .header("CF-Client-Version", CLIENT_VERSION)
        .bearer_auth(&reg.token)
        .json(&serde_json::json!({ "warp_enabled": true }))
        .send()
        .await
        .context("enable warp")?;
    if !patch.status().is_success() {
        bail!("cloudflare refused to enable warp: {}", patch.status());
    }

    let license = license.trim();
    if !license.is_empty() {
        let resp = http
            .put(format!("{API_BASE}/reg/{}/account", reg.id))
            .header("CF-Client-Version", CLIENT_VERSION)
            .bearer_auth(&reg.token)
            .json(&serde_json::json!({ "license": license }))
            .send()
            .await
            .context("apply warp+ license")?;
        if !resp.status().is_success() {
            let body = resp.text().await.unwrap_or_default();
            return Err(BadLicense(license_error(&body)).into());
        }
    }

    build_registration(secret_key, reg)
}

/// Cloudflare's own words for a rejected license — `{"errors":[{"message":
/// "Invalid license"}]}`. Repeating them beats a status code: the operator is
/// looking at the key they just pasted, and "Invalid license" says what to do
/// about it.
fn license_error(body: &str) -> String {
    serde_json::from_str::<serde_json::Value>(body)
        .ok()
        .and_then(|v| {
            v.get("errors")?
                .get(0)?
                .get("message")?
                .as_str()
                .map(str::to_owned)
        })
        .unwrap_or_else(|| "cloudflare rejected the license".to_owned())
}

/// Turn a registration response into the fields an outbound needs. Split out
/// so the mapping is testable without the network.
fn build_registration(secret_key: String, reg: RegResponse) -> anyhow::Result<WarpRegistration> {
    let peer = reg
        .config
        .peers
        .into_iter()
        .next()
        .context("registration carried no peer")?;
    // Prefer the name: Cloudflare moves the address behind it, and a pinned
    // v4 goes dark when it does.
    let endpoint = peer
        .endpoint
        .host
        .or(peer.endpoint.v4)
        .context("peer carried no endpoint")?;

    let v4 = reg
        .config
        .interface
        .addresses
        .v4
        .context("registration carried no v4 address")?;
    let mut addresses = vec![format!("{v4}/32")];
    if let Some(v6) = reg.config.interface.addresses.v6 {
        addresses.push(format!("{v6}/128"));
    }

    // `client_id` is four base64 characters — the three bytes that go into
    // every packet's reserved field.
    let reserved = STANDARD
        .decode(reg.config.client_id.as_bytes())
        .context("client_id is not base64")?;
    if reserved.len() != 3 {
        bail!("client_id decoded to {} bytes, expected 3", reserved.len());
    }

    Ok(WarpRegistration {
        secret_key,
        peer_public_key: peer.public_key,
        endpoint,
        addresses,
        reserved,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A registration response, trimmed to the fields the panel reads, with
    /// the shape Cloudflare actually returns.
    const SAMPLE: &str = r#"{
        "id": "t.00000000-0000-0000-0000-000000000000",
        "token": "00000000-0000-0000-0000-000000000000",
        "config": {
            "client_id": "kGWq",
            "peers": [{
                "public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
                "endpoint": {
                    "v4": "162.159.192.1:2408",
                    "v6": "[2606:4700:d0::a29f:c001]:2408",
                    "host": "engage.cloudflareclient.com:2408"
                }
            }],
            "interface": { "addresses": { "v4": "172.16.0.2", "v6": "2606:4700:110:8a1b::1" } }
        }
    }"#;

    #[test]
    fn a_registration_becomes_a_dialable_tunnel() {
        let reg: RegResponse = serde_json::from_str(SAMPLE).expect("sample parses");
        let ob = build_registration("cGxhY2Vob2xkZXI=".to_owned(), reg)
            .expect("mapping")
            .into_outbound();

        // The name, not the v4 — the address behind it moves.
        assert_eq!(ob.endpoint, "engage.cloudflareclient.com:2408");
        assert_eq!(ob.address, ["172.16.0.2/32", "2606:4700:110:8a1b::1/128"]);
        // Three bytes, and they are what the edge matches on: a tunnel that
        // sends the wrong ones is answered with silence, which is the hardest
        // possible failure to read from the outside.
        assert_eq!(ob.reserved, [144, 101, 170]);
        assert_eq!(ob.mtu, 1280);
        assert!(ob.warp);
    }

    /// Cloudflare has answered with an empty peer list before now; that must
    /// be an error the operator sees, not an outbound with no peer that xray
    /// accepts and quietly drops every packet into.
    #[test]
    fn a_registration_without_a_peer_is_refused() {
        let broken = SAMPLE.replace(r#""peers": [{"#, r#""peers": [], "ignored": [{"#);
        let reg: RegResponse = serde_json::from_str(&broken).expect("sample parses");
        assert!(build_registration(String::new(), reg).is_err());
    }
}
