// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Public view of a client row.
 */
export type Client = { id: string, inbound_id: string, email: string, 
/**
 * VLESS UUID — the client's secret. Plain text in the API because the
 * operator needs it to assemble a share-link. Frontend should treat it
 * like a password (mask by default, eye-toggle to reveal).
 */
uuid: string, 
/**
 * Hysteria 2 auth secret. `None` for VLESS clients (ignored). For
 * hysteria inbounds: the per-user string the client sends in the
 * HTTP/3 Auth header. `None` falls back to `uuid` on the wire so
 * pre-hysteria rows keep working without manual backfill.
 */
auth: string | null, 
/**
 * `None` → inherit the inbound's `vless_flow`. Explicit `Some` overrides.
 */
flow: string | null, enabled: boolean, note: string | null, 
/**
 * Hard cap in bytes on the lifetime sum of uplink + downlink. `None` /
 * `NULL` ≡ no quota. When crossed, the stats poller flips `enabled` off
 * with `disabled_reason = "quota"` and tells xray to drop the user.
 */
traffic_limit_bytes: number | null, 
/**
 * Why the row is currently `enabled = false`. `None` while enabled (or
 * for rows that have never been disabled). The operator-visible values:
 *   * `"manual"` — operator clicked the toggle / saved with off
 *   * `"quota"` — the poller hit `traffic_limit_bytes`
 *   * `"expired"` — the poller passed `expires_at`
 *
 * The split lets "reset traffic" re-enable a quota client while
 * leaving manually-disabled ones alone.
 */
disabled_reason: string | null, 
/**
 * Absolute expiry instant as a UTC `YYYY-MM-DD HH:MM:SS` string (the
 * `datetime('now')` shape). `None` / `NULL` ≡ never expires. When it
 * passes, the stats poller flips `enabled` off with
 * `disabled_reason = "expired"` and tells xray to drop the user;
 * clearing or extending it re-enables the row.
 */
expires_at: string | null, 
/**
 * Per-row subscription token. The public `GET /sub/{token}` endpoint
 * resolves it to the client, then aggregates every share-link for
 * rows with the same `email` across all inbounds — that's how one
 * URL maps to "all my configs" in v2rayN / Hiddify / sing-box.
 * 32 lowercase hex chars (16 random bytes). Rotated via
 * `POST /api/clients/{id}/rotate-sub-token`.
 */
sub_token: string, created_at: string, updated_at: string, };

/**
 * Body for `POST /api/clients/bulk-assign` — the "give this user access
 * to N inbounds in one shot" operation. `inbound_ids` is the desired
 * target set: rows for inbounds present in the set are created (or
 * updated to match the supplied fields), rows for the email's other
 * inbounds are torn down. UUID/auth/flow/note/limit are shared across
 * every produced row so the user has a consistent identity in every
 * client app — and so the same subscription bundle resolves to N
 * distinct share-links instead of N permutations of credentials.
 */
export type ClientBulkAssign = { email: string, 
/**
 * Target inbound set. Must contain at least one entry — the bulk
 * op never deletes the user entirely (use the per-row DELETE for
 * that, which is more explicit about what's being removed).
 */
inbound_ids: Array<string>, uuid: string | null, auth: string | null, flow: string | null, note: string | null, traffic_limit_bytes: number | null, expires_at: string | null, };

/**
 * Result of a `POST /api/clients/bulk-assign`. Three sets so the
 * frontend can show "+3 created, 1 updated, 1 removed" without
 * diffing the listing itself, plus a `xray_failures` channel for
 * the post-commit gRPC sync — DB always wins, but the operator
 * needs to know if xray didn't pick up a change so they can hit
 * "Restart xray" before users notice the drift.
 */
export type ClientBulkAssignResult = { 
/**
 * Newly-inserted rows (one per `inbound_id` that didn't already
 * have an assignment for this email).
 */
created: Array<Client>, 
/**
 * Existing rows whose fields were rewritten to match the bulk body.
 */
updated: Array<Client>, 
/**
 * Rows that were dropped because their inbound is no longer in
 * the target set. Returned as `(client_id, inbound_id)` rather
 * than the full Client — they don't exist anymore on the server.
 */
removed: Array<ClientBulkRemoved>, 
/**
 * Per-inbound xray gRPC errors. Empty in the happy path. The DB
 * is consistent regardless — these are reconciliation hints.
 */
xray_failures: Array<ClientBulkXrayFailure>, };

export type ClientBulkRemoved = { id: string, inbound_id: string, };

export type ClientBulkXrayFailure = { inbound_id: string, inbound_tag: string, 
/**
 * Operator-readable summary; full details live in backend logs.
 */
message: string, };

/**
 * Body for `POST /api/inbounds/{inbound_id}/clients`.
 *
 * `uuid` is server-generated when omitted (`Uuid::new_v4()`); the operator
 * can also paste an existing UUID to migrate users from another panel.
 */
export type ClientCreate = { email: string, uuid: string | null, 
/**
 * Hysteria 2 per-user auth string. Server-generated if omitted on a
 * hysteria inbound (random 32-char base64); ignored on a vless inbound.
 */
auth: string | null, flow: string | null, note: string | null, 
/**
 * Optional traffic cap in bytes. `None` ≡ no cap; the field can be
 * added later via PATCH if the operator decides to enforce one.
 */
traffic_limit_bytes: number | null, 
/**
 * Optional absolute expiry, ISO-8601 from the client; normalized to the
 * `datetime('now')` shape on write. `None` ≡ never expires.
 */
expires_at: string | null, };

/**
 * Body for the top-level `POST /api/clients`.
 *
 * Distinct from `ClientCreate` because the nested route picks `inbound_id`
 * up from the URL (`/api/inbounds/{inbound_id}/clients`), whereas the
 * global route needs it explicitly in the body. Field shape is otherwise
 * identical so the frontend can reuse most of its create-form logic.
 */
export type ClientCreateGlobal = { inbound_id: string, email: string, uuid: string | null, auth: string | null, flow: string | null, note: string | null, traffic_limit_bytes: number | null, expires_at: string | null, };

/**
 * Body for `PATCH /api/inbounds/{inbound_id}/clients/{client_id}`
 * and `PATCH /api/clients/{id}`.
 */
export type ClientUpdate = { email: string | null, uuid: string | null, 
/**
 * Hysteria 2 auth string. Same meaning as ClientCreate.auth — omit
 * to leave unchanged; explicit non-empty string replaces it. Setting
 * to empty string clears it (rare, but the operator may want to
 * switch a row back to uuid-fallback behaviour).
 */
auth: string | null, flow: string | null, enabled: boolean | null, note: string | null, 
/**
 * Tri-state PATCH semantics — `Set(n)` writes the cap, `Clear` drops
 * it back to unlimited, `Unchanged` leaves the column alone.
 * `#[serde(default)]` is what makes "key absent" deserialize to
 * `Unchanged`; an explicit `null` from the wire becomes `Clear` via
 * `PatchField`'s own deserializer.
 */
traffic_limit_bytes: number | null | undefined, 
/**
 * Tri-state PATCH for the expiry instant. Same semantics as
 * `traffic_limit_bytes`: `Set` writes, `Clear` (explicit null) drops to
 * never-expires, `Unchanged` leaves it. ISO-8601 in, normalized on write.
 */
expires_at: string | null | undefined, };

export type ShareLinkResponse = { link: string, 
/**
 * Host portion the panel guessed for the share-link. Surfaced so the
 * frontend can warn the operator when it falls back to a private IP
 * or a stale value.
 */
host: string, };
