// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tagged-enum operator-facing `FinalMask` configuration. `None` is the
 * "no obfuscation" default — the column is non-nullable but its
 * default JSON blob always decodes to `Self::None`.
 *
 * Per-variant transport scope (xray dispatches on the actual socket
 * type at handshake time):
 *   * `Sudoku`   — both TCP and UDP. Same Config goes into both
 *     `tcpmasks` and `udpmasks`.
 *   * `Fragment` — TCP, but CLIENT-ONLY. It's asymmetric (the client
 *     fragments its own `ClientHello`; the server just reassembles over
 *     TCP), so the orchestrator deliberately does NOT add it to the
 *     server's `tcpmasks` — it only rides the share-link's `fm=`. A
 *     server-side fragment wrapper would be pointless and, under Reality,
 *     panics xray (`fragmentConn is not reality.CloseWriteConn`).
 *   * `Noise`    — UDP only. Populates only `udpmasks`; ignored for
 *     vless/reality TCP inbounds. Most useful for QUIC/Hysteria
 *     where a noise prefix breaks fingerprinting.
 */
export type FinalMask = { "kind": "none" } | { "kind": "sudoku" } & SudokuParams | { "kind": "fragment" } & FragmentParams | { "kind": "noise" } & NoiseParams | { "kind": "salamander" } & SalamanderParams;

/**
 * Fragment finalmask knobs (xray-core v26.6.22 #6334). `lengths`/`delays`
 * are PER-SEGMENT parallel arrays: segment `i` is `lengths_min[i]..
 * lengths_max[i]` bytes long and is followed by a `delays_min[i]..
 * delays_max[i]` ms pause; the last entry repeats for all further segments.
 * `packets` selects which packets to fragment (0/1 ≡ the `tlshello`
 * shortcut). Empty arrays ≡ "use xray's default". xray rejects a final
 * `lengths` entry whose min is 0, so the active form keeps a positive last
 * min.
 */
export type FragmentParams = { packets_from: number | null, packets_to: number | null, 
/**
 * Per-segment chunk-length range, min side. Paired index-for-index with
 * `lengths_max`.
 */
lengths_min: number[], lengths_max: number[], 
/**
 * Per-segment inter-chunk delay range in ms, min side. Paired with
 * `delays_max`.
 */
delays_min: number[], delays_max: number[], max_split_min: number | null, max_split_max: number | null, };

/**
 * One noise item. xray builds a datagram prefix from EITHER a literal
 * `packet` (hex) OR `rand_min..rand_max` random bytes — never both on the
 * same item (xray's conf parser errors on `len(packet) > 0 && rand.To > 0`).
 * `rand_range_min/max` (the byte-value range) is pinned to xray's 0..255
 * conf default at build time. `delay_min..delay_max` is an optional per-item
 * pause (ms) before the item is emitted; `0..0` ≡ no delay.
 */
export type NoiseItem = { 
/**
 * Hex-encoded literal prefix bytes. Empty ≡ random-bytes mode.
 */
packet_hex: string, 
/**
 * Random byte count appended when there's no literal prefix.
 */
rand_min: number | null, rand_max: number | null, 
/**
 * Per-item send delay (ms). `0..0` ≡ no delay.
 */
delay_min: number | null, delay_max: number | null, };

/**
 * Noise finalmask knobs. xray's wire shape is a list of `Item`s plus a
 * reset interval (rotates which item is used between datagrams). We expose
 * the full item list with per-item random-length and delay ranges — covers
 * both the common "N random bytes per datagram" QUIC-masking case and
 * multi-item sequences (e.g. a literal fake-handshake item followed by a
 * random-filler item, each with its own delay).
 *
 * Older rows stored a single item inline (`packet_hex`/`rand_min`/`rand_max`
 * at the top level). The hand-written [`Deserialize`] (below) folds that
 * legacy shape into `items` DURING deserialization via [`NoiseParamsRepr`],
 * so EVERY read path (API GET, config-gen reconcile, share-link, and request
 * bodies) sees one shape with no per-call-site `normalize()` to forget — no
 * data migration needed, and the serialized form is always the new `items[]`
 * layout.
 */
export type NoiseParams = { 
/**
 * Ordered list of noise items applied per datagram.
 */
items: Array<NoiseItem>, 
/**
 * Datagram count after which xray rotates noise state. `0..0` ≡ xray
 * default. Not surfaced in the UI (pinned null → 0).
 */
reset_min: number | null, reset_max: number | null, };

/**
 * Salamander finalmask knobs. Hysteria 2's obfs is a single shared
 * password; the packet-size window (Gecko variant) is left at xray's
 * default for v1.
 */
export type SalamanderParams = { 
/**
 * Shared obfuscation password. Required; empty ≡ disabled (the
 * orchestrator emits no mask, and the share-link omits `obfs=`).
 */
password: string, };

/**
 * Knobs surfaced to the operator. Mirrors the upstream proto field
 * names (`snake_case` Rust ↔ camelCase JSON) so the JSON round-trips
 * cleanly into xray's parser when we build the share-link payload.
 */
export type SudokuParams = { 
/**
 * Shared secret. Required; empty string is treated as "disabled"
 * downstream by the orchestrator (we just don't emit the mask).
 */
password: string, 
/**
 * `prefer_entropy` (default) or `prefer_ascii`. Empty ≡ default.
 */
ascii: string, 
/**
 * Optional custom lookup table override (advanced — leave empty
 * for the built-in default).
 */
custom_table: string, 
/**
 * Min padding bytes per packet. Empty ≡ xray default.
 */
padding_min: number | null, 
/**
 * Max padding bytes per packet. Empty ≡ xray default.
 */
padding_max: number | null, 
/**
 * Optional list of additional lookup tables (advanced).
 */
custom_tables: Array<string>, };
