// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of refreshing one file.
 */
export type GeoFileOutcome = { name: string, 
/**
 * False when the downloaded bytes hashed identically to what is already
 * on disk — the common case on a daily check, and the reason a refresh
 * does not restart xray every night.
 */
changed: boolean, size_bytes: number, sha256: string, };

/**
 * What one file on disk looks like right now. `sha256` is computed from the
 * bytes, not remembered — a file replaced by hand outside the panel still
 * reports the truth.
 */
export type GeoFileStatus = { name: string, present: boolean, size_bytes: number, 
/**
 * RFC 3339, or empty when the file is missing.
 */
modified_at: string, 
/**
 * Full lowercase hex; the UI shows a prefix.
 */
sha256: string, };

/**
 * Geofile panel: what is on disk, where it should come from, and whether the
 * panel refreshes it on its own. Deliberately separate from `/settings/panel`
 * — this belongs to the xray-updates surface, and folding it into that big
 * row would make every unrelated settings save carry it.
 */
export type GeoPanel = { 
/**
 * A preset id, `custom`, or `xray` for "whatever the release archive
 * installed".
 */
source: string, custom_geoip_url: string, custom_geosite_url: string, auto_update: boolean, 
/**
 * RFC 3339 of the last refresh that WROTE something; empty if never.
 */
updated_at: string, 
/**
 * Preset ids this build knows, so the UI can never offer one the backend
 * would reject.
 */
sources: Array<string>, 
/**
 * The files on disk are newer than what the running xray parsed — it needs
 * a restart before the new lists mean anything.
 */
apply_pending: boolean, files: Array<GeoFileStatus>, };

export type GeoUpdateResult = { outcomes: Array<GeoFileOutcome>, 
/**
 * True when at least one file's bytes differed and it was replaced.
 */
changed: boolean, 
/**
 * True when xray was running and got restarted to pick the new files up.
 */
restarted: boolean, };
