// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalMask } from "./finalmask";
import type { ProtocolConfig } from "./protocol";
import type { SecurityConfig } from "./security";
import type { TransportConfig } from "./transport";

/**
 * One inbound row. Serialized 1:1 to the frontend; persisted with the
 * three layer blobs sitting in their own DB columns so `SQLite`'s JSON1
 * functions can poke at them when needed (admin shell debugging,
 * future migrations).
 */
export type Inbound = { id: string, tag: string, enabled: boolean, listen: string, port: number, protocol: ProtocolConfig, transport: TransportConfig, security: SecurityConfig, sniffing: Sniffing, 
/**
 * Wire-level last-stage obfuscation. `FinalMask::None` (default)
 * means the column's JSON blob is `{"kind":"none"}` — xray gets
 * no `streamSettings.finalmask` and the share-link gets no `fm=`
 * param. Active variants must be configured symmetrically in the
 * client app (subscription bundle carries the settings).
 */
finalmask: FinalMask, 
/**
 * Socket-level options (`streamSettings.sockopt`). Default (all
 * fields empty) emits no sockopt block, so the wire output is
 * unchanged for inbounds that never touch it. Most relevant field
 * is `trusted_x_forwarded_for`, which xray now warns about on
 * XHTTP/WS/HttpUpgrade inbounds (xray-core #6159).
 */
sockopt: SocketOpt, created_at: string, updated_at: string, };

/**
 * Body for `POST /api/inbounds`. The three layer blocks are required;
 * `listen` falls back to `0.0.0.0` and `sniffing` to its default when
 * omitted so the frontend's create modal stays terse.
 */
export type InboundCreate = { tag: string, 
/**
 * Optional; defaults to "0.0.0.0".
 */
listen: string | null, port: number, protocol: ProtocolConfig, transport: TransportConfig, security: SecurityConfig, 
/**
 * Optional; defaults to `Sniffing::default()`.
 */
sniffing: Sniffing | null, 
/**
 * Optional; defaults to `FinalMask::None` (no obfuscation).
 */
finalmask: FinalMask | null, 
/**
 * Optional; defaults to an empty (inactive) `SocketOpt`.
 */
sockopt: SocketOpt | null, };

/**
 * Body for `PATCH /api/inbounds/{id}`. Each layer is independently
 * replaceable — sending `transport: { ... }` swaps the whole transport
 * block; omitting it leaves the existing column untouched. There's no
 * merge-at-field-level semantic: callers that need it (e.g. flip one
 * `ws_path`) read the inbound, mutate the relevant layer in JS, and
 * PATCH the whole layer back.
 */
export type InboundUpdate = { tag: string | null, enabled: boolean | null, listen: string | null, port: number | null, protocol: ProtocolConfig | null, transport: TransportConfig | null, security: SecurityConfig | null, sniffing: Sniffing | null, finalmask: FinalMask | null, sockopt: SocketOpt | null, };

/**
 * Sniffing config — when xray inspects payload to derive
 * SNI / HTTP-host / etc. for routing decisions.
 */
export type Sniffing = { enabled: boolean, 
/**
 * Subset of `["http", "tls", "fakedns", "quic"]`. Empty array is
 * equivalent to `enabled == false`.
 */
dest_override: Array<string>, };

/**
 * Operator-facing socket options. Every field is optional; an instance
 * where nothing is set is inactive and contributes no `socket_settings`.
 */
export type SocketOpt = { 
/**
 * CIDRs / IPs of trusted upstream proxies whose `X-Forwarded-For`
 * header xray may believe. Empty = trust nothing (the safe default
 * for a directly-exposed inbound). xray-core #6159 warns when this
 * is unset on XHTTP / WS / `HttpUpgrade` inbounds.
 */
trusted_x_forwarded_for: Array<string>, 
/**
 * TCP keepalive probe interval (seconds). 0 / unset ≡ xray default.
 */
tcp_keep_alive_interval: number | null, 
/**
 * Idle time before the first keepalive probe (seconds). 0 / unset ≡
 * xray default.
 */
tcp_keep_alive_idle: number | null, 
/**
 * Enable multipath TCP (both peers must support it).
 */
tcp_mptcp: boolean, 
/**
 * Accept a PROXY-protocol header from a trusted upstream LB / proxy so
 * xray recovers the real client IP. Enable only when something in
 * front actually prepends one.
 */
accept_proxy_protocol: boolean, 
/**
 * TCP Fast Open. Maps straight to xray's `tfo`: `None`/0 leaves the OS
 * default, a positive value enables TFO with that queue length (256 =
 * typical "on"), a negative value force-disables it. The UI offers
 * Default / Enabled (256) / Disabled (-1).
 */
tcp_fast_open: number | null, 
/**
 * Listen IPv6-only on a `[::]` socket (`IPV6_V6ONLY`). Off ≡ dual-stack.
 */
v6only: boolean, };
