// Barrel re-export of backend-generated TypeScript types. Each sibling
// `.ts` is auto-generated by ts-rs from the Rust types annotated with
// `#[ts(export)]` — do not hand-edit those files. This barrel is
// hand-maintained: re-export only what frontend consumers actually
// import. Discriminator enums (`TransportKind`, `SecurityKind`) and
// internal variant types (`TcpTransport`, `NoneSecurity`, ...) stay in
// their sibling files because the discriminated-union parent types
// reference them, but consumers never need to name them directly.
//
// Consumer code should only ever import from this barrel:
//   import { Inbound, VlessProtocol, TransportConfig } from '@/api/types';

export type {
  Inbound,
  InboundCreate,
  InboundTraffic,
  InboundUpdate,
  Sniffing,
  SocketOpt,
} from './inbound';

export type {
  ProtocolConfig,
  VlessProtocol,
  VlessFlow,
  VlessEncryptionMode,
  VlessEncryptionAuth,
  VlessXorMode,
  VlessFallback,
  VlessFallbackType,
  WireguardProtocol,
  WireguardKeypair,
} from './protocol';

export type {
  TransportConfig,
  WsTransport,
  XhttpTransport,
  XhttpMode,
  HysteriaTransport,
  HysteriaMasquerade,
  QuicParams,
  QuicCongestion,
  UdpHop,
} from './transport';

export type { FinalMask, NoiseItem, XmcProfile } from './finalmask';

export type {
  CustomOutbound,
  OutboundTestResult,
  OutboundTraffic,
} from './outbound';

export type {
  SecurityConfig,
  TlsSecurity,
  TlsCertificate,
  TlsCertSource,
  TlsCertUsage,
  EchKeyBundle,
} from './security';

export type {
  Client,
  ClientBulkAssign,
  ClientBulkAssignResult,
  ShareLinkResponse,
} from './client';

export type { TrafficSnapshot, DashboardOverview, XrayRelease, LogEntry } from './stats';

export type {
  UserView,
  PanelSettings,
  PanelSettingsUpdate,
  DnsHost,
  DnsServer,
  RoutingRule,
  SystemToken,
} from './settings';
