// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinalMask } from "./finalmask";
import type { VlessEncryptionMode, VlessXorMode } from "./protocol";
import type { SecurityConfig } from "./security";
import type { TransportConfig } from "./transport";

/**
 * One custom outbound. Its `tag` is the routing-rule target; reject the
 * reserved tags (direct / blocked / direct-ipv4 / api) at save time.
 */
export type CustomOutbound = { id: string, tag: string, enabled: boolean, protocol: OutboundProtocolConfig, 
/**
 * Wire transport (tcp / ws / xhttp / hysteria) — reused from inbounds.
 */
transport: TransportConfig, 
/**
 * Stream security (none / tls / reality) — reused; the client-facing
 * fields are emitted (serverName/fingerprint/publicKey/shortId).
 */
security: SecurityConfig, 
/**
 * Wire-level socket obfuscation to MIRROR the upstream. Sudoku is a
 * symmetric/stateful cipher — a relay to a Sudoku inbound MUST run the
 * identical config or the server drops it. `#[serde(default)]` keeps
 * rows written before this field landed deserializing.
 */
finalmask: FinalMask, 
/**
 * Connection multiplexing (optional).
 */
mux: OutboundMux, 
/**
 * `sendThrough` — source bind: "" | IP | CIDR | "origin" | "srcip".
 */
send_through: string, 
/**
 * `proxySettings.tag` — chain this outbound through another outbound by
 * tag. "" = no chaining.
 */
proxy_tag: string, created_at: string, updated_at: string, };

/**
 * Hysteria 2 client settings → xray `protocol: "hysteria"` settings, which is
 * just `ClientConfig { server: { address, port } }`. Everything
 * else is reused as-is by the orchestrator, mirroring the inbound pairing:
 * the auth (password) and QUIC / masquerade knobs ride on the paired
 * `hysteria` transport (`HysteriaTransport.auth` etc.), and client TLS
 * (serverName / allowInsecure / pinned cert) on the `security` block.
 */
export type HysteriaOutbound = { 
/**
 * Remote server address (domain or IP).
 */
address: string, 
/**
 * Remote server port.
 */
port: number, };

/**
 * Mux settings → xray `mux`. Disabled by default.
 */
export type OutboundMux = { enabled: boolean, 
/**
 * `concurrency`: <0 disables, 0 = xray default (8), >0 custom.
 */
concurrency: number, };

/**
 * Protocol-specific outbound settings. Tagged enum mirrors the inbound
 * `ProtocolConfig` shape so the frontend form can dispatch the same way.
 */
export type OutboundProtocolConfig = { "kind": "vless" } & VlessOutbound | { "kind": "hysteria" } & HysteriaOutbound | { "kind": "wireguard" } & WireguardOutbound;

export type OutboundTestResult = { 
/**
 * True when the request to `xray_test_url` egressed through the outbound
 * and returned.
 */
ok: boolean, latency_ms: number | null, 
/**
 * Egress IP the test endpoint saw (i.e. where the outbound exits).
 */
exit_ip: string | null, 
/**
 * Egress datacenter / country code (Cloudflare `loc=`).
 */
exit_loc: string | null, error: string | null, };

/**
 * Per-outbound lifetime traffic (`tag -> {uplink, downlink}`), including the
 * built-ins (direct/blocked/direct-ipv4). Cumulative totals persisted by the
 * [`crate::outbound_traffic`] poller — they survive xray restarts, unlike the
 * session-only counters xray exposes directly.
 */
export type OutboundTraffic = { uplink: number, downlink: number, };

/**
 * VLESS client settings → xray `settings.vnext[0]`. One endpoint, one user.
 */
export type VlessOutbound = { 
/**
 * Remote server address (domain or IP).
 */
address: string, 
/**
 * Remote server port.
 */
port: number, 
/**
 * User UUID.
 */
id: string, 
/**
 * XTLS flow: "" or "xtls-rprx-vision".
 */
flow: string, 
/**
 * VLESS Reverse Proxy tag (xray 26.7.11+). Non-empty makes this outbound a
 * reverse BRIDGE: it dials the portal with the reverse command and offers
 * itself as a tunnel under this tag. Empty ≡ a normal relay outbound. The
 * portal side is a VLESS inbound whose client carries the same tag.
 */
reverse_tag: string, 
/**
 * Application-layer encryption to MATCH the upstream server. `None` =
 * plain VLESS (the common case). `mlkem768x25519plus` is the
 * post-quantum cipher — it needs the server's public `client_key` plus
 * the same xor mode / padding the server advertises. The orchestrator
 * turns these into the `Account.{encryption,xor_mode,seconds,padding}`
 * proto fields via the shared `vless_client_encryption_fields`.
 */
encryption_mode: VlessEncryptionMode, encryption_xor_mode: VlessXorMode | null, 
/**
 * The upstream's PUBLIC `client_key` (base64-url) — the same value the
 * server embeds in its share-links, NOT the server's private key.
 */
encryption_client_key: string | null, encryption_padding: string | null, };

/**
 * Optional body of the WARP registration: a WARP+ license key, or nothing at
 * all for a free tunnel.
 */
export type WarpRequest = { license: string, };

/**
 * A `WireGuard` tunnel used as an outbound — xray dials it in userspace, so no
 * kernel interface and no root are involved.
 *
 * This is also the shape a Cloudflare WARP tunnel takes: WARP is ordinary
 * `WireGuard` plus `reserved`, three bytes derived from the client id that
 * Cloudflare's edge uses to tell registrations apart. `POST /outbounds/warp`
 * fills every field in here from a registration; a hand-written peer leaves
 * `reserved` empty.
 *
 * Keys are held the way `WireGuard` writes them (base64, 44 chars). The core's
 * proto wants hex, and the orchestrator converts on the way out — mirroring
 * `ParseWireGuardKey` in `infra/conf/wireguard.go`.
 */
export type WireguardOutbound = { 
/**
 * Our private key.
 */
secret_key: string, 
/**
 * The addresses the tunnel gives us, with prefix — the v4 one always, the
 * v6 one when the peer hands one out.
 */
address: Array<string>, 
/**
 * The peer's public key.
 */
peer_public_key: string, 
/**
 * `host:port` of the peer.
 */
endpoint: string, 
/**
 * WARP's client-id bytes. Empty for a plain `WireGuard` peer; a WARP tunnel
 * without them is answered by the edge with silence.
 */
reserved: Array<number>, 
/**
 * 0 = the core's default (1420). WARP wants 1280.
 */
mtu: number, 
/**
 * Keepalive seconds; 0 = off.
 */
keep_alive: number, 
/**
 * Registered through the panel's WARP button rather than typed in. Only
 * affects what the UI says about the row.
 */
warp: boolean, };
