// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HysteriaProtocol = Record<symbol, never>;

/**
 * Tagged-union of every protocol variant. Lives on `Inbound` as the
 * `protocol` field; serializes to a single JSON blob in the DB.
 */
export type ProtocolConfig = { "kind": "vless" } & VlessProtocol | { "kind": "hysteria2" } & HysteriaProtocol;

export type VlessEncryptionAuth = "mlkem768" | "x25519";

/**
 * A VLESS Encryption keypair (post-quantum or X25519 variant of
 * `mlkem768x25519plus`). Both halves are base64-url no-pad strings,
 * directly usable as the trailing `<key>` segment of the
 * `mlkem768x25519plus.<mode>.<seconds>[.<padding>].<key>` wire format
 * — that's the canonical encoding `xray vlessenc` emits.
 */
export type VlessEncryptionKeypair = { 
/**
 * Server's private half. SECRET — never log.
 */
server_key: string, 
/**
 * Client's public half. Embedded in every share-link.
 */
client_key: string, };

/**
 * VLESS Encryption mode (xray-core's `mlkem768x25519plus` application-
 * layer cipher, on top of TLS/Reality). `None` is the historical default.
 */
export type VlessEncryptionMode = "none" | "mlkem768x25519plus";

/**
 * One fallback route on a VLESS inbound. xray-core treats fallbacks as
 * a 3-level routing matrix keyed on (SNI substring, ALPN, HTTP-path),
 * firing when a connection makes it through TLS/Reality but fails to
 * produce a valid VLESS header within ~18 bytes — i.e. the probe is
 * most likely a real HTTP/H2 request from a search engine, scanner,
 * or genuine browser. The matched fallback forwards the raw bytes to
 * `dest` so the IP can credibly host both VLESS and a real web app.
 *
 * All match fields default to empty (= wildcard / "any"); only `dest`
 * is meaningful in the simplest single-fallback case. Mutually
 * exclusive with `VlessEncryption` (xray errors at startup with
 * `fallbacks can not be used together with decryption`).
 */
export type VlessFallback = { 
/**
 * Operator label. Not used for routing — xray groups by SNI
 * substring through this field, but our UI uses empty string for
 * the default route and a substring for named virtual hosts.
 */
name: string, 
/**
 * ALPN match: `""` = any, `"h2"`, `"http/1.1"`. Path-based
 * matching is documented as unreliable under `h2`.
 */
alpn: string, 
/**
 * HTTP-path match. Empty = any. Non-empty MUST start with `/` or
 * xray's config parser rejects the inbound.
 */
path: string, 
/**
 * Destination kind. See `VlessFallbackType`.
 */
type: VlessFallbackType, 
/**
 * Where to forward. Format depends on `kind`:
 * * tcp:   `host:port`, IPv4 ok, IPv6 must be bracketed
 * * unix:  absolute filesystem path or `@abstract` socket name
 * * serve: only `serve-ws-none` is documented today
 */
dest: string, 
/**
 * PROXY-protocol version to prepend to forwarded bytes so the
 * downstream sees the real client IP. `0` = off, `1` = text v1,
 * `2` = binary v2. Anything > 2 is rejected by xray.
 */
xver: number, };

/**
 * Destination type for a VLESS fallback. Mirrors xray's auto-inference
 * of the proto-level `type` field — operator picks explicitly so the
 * panel doesn't have to replicate xray's heuristics (port-number ↔ tcp,
 * abstract-socket prefix ↔ unix, etc.). Empty defaults to `Tcp` at
 * proto build time.
 */
export type VlessFallbackType = "tcp" | "unix" | "serve";

/**
 * VLESS flow setting. None = plain VLESS, `XtlsRprxVision` = the XTLS
 * "Vision" optimisation (TCP-only, mostly used with Reality).
 */
export type VlessFlow = "none" | "xtls-rprx-vision";

/**
 * VLESS protocol config — everything the panel stores in the
 * `protocol_config` JSON blob for a VLESS inbound.
 */
export type VlessProtocol = { flow: VlessFlow, 
/**
 * Encryption mode for the application-layer cipher. `None` keeps
 * historical plain-VLESS-over-TLS/Reality behaviour.
 */
encryption_mode: VlessEncryptionMode, encryption_auth: VlessEncryptionAuth | null, encryption_xor_mode: VlessXorMode | null, encryption_seconds_from: number | null, encryption_seconds_to: number | null, encryption_padding: string | null, 
/**
 * SECRET. base64-url. Server's private half of the ML-KEM/X25519
 * keypair. Never logged.
 */
encryption_server_key: string | null, 
/**
 * Public. base64-url. Embedded in share-links.
 */
encryption_client_key: string | null, 
/**
 * Optional fallback table. Empty = no fallbacks (the historical
 * behaviour). `#[serde(default)]` keeps DB rows written before
 * this field landed deserialising cleanly.
 */
fallbacks: Array<VlessFallback>, };

export type VlessXorMode = "native" | "xorpub" | "random";
