// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A freshly-generated ECH (Encrypted Client Hello) key bundle. Both halves
 * are `base64.StdEncoding` strings — exactly what `xray tls ech` prints and
 * what the `tls::Config.ech_server_keys` / `ech_config_list` fields expect.
 *
 * * `ech_server_keys` — secret. Goes into the inbound's TLS settings; the
 *   panel sends this byte-stream (after base64-decode) to xray as
 *   `ech_server_keys` in the proto. **Never log.**
 * * `ech_config_list` — public. Clients embed this in their TLS Client
 *   Hello to negotiate ECH. We currently surface it for the operator to
 *   copy into client config; the panel doesn't persist it because xray
 *   derives it from `ech_server_keys` on boot.
 */
export type EchKeyBundle = { ech_server_keys: string, ech_config_list: string, };

/**
 * "None" — plaintext over the chosen transport. Useful behind a CDN
 * or reverse proxy that terminates TLS. xray treats empty
 * `security_type` as no security layer; `build_settings` returns
 * `None` so the orchestrator leaves `security_settings` unpopulated.
 * Lives in this module (rather than its own file) because the
 * struct is field-less and the impl is three trivial methods.
 */
export type NoneSecurity = Record<symbol, never>;

/**
 * A freshly-generated Reality keypair, both halves encoded as base64-url
 * without padding (43-char strings, like `xray x25519` output).
 *
 * Body-carried like `VlessEncryptionKeypair`: the frontend pre-generates a
 * pair via `POST /api/keygen/reality-keypair` so the operator sees the
 * `public_key` the moment they pick Reality on the create form, holds both
 * halves in form state, and sends them back with the inbound. On save the
 * server re-derives the public from the private, so a hand-crafted request
 * can't slip in a mismatched pair.
 */
export type RealityKeypair = { 
/**
 * Server's private half. SECRET — never log.
 */
private_key: string, public_key: string, };

export type RealitySecurity = { 
/**
 * Target site the inbound impersonates ("dest" in xray docs).
 * e.g. "www.cloudflare.com:443". xray opens a real TLS connection
 * to this host during MITM moments.
 */
dest: string, 
/**
 * Allowed SNI values clients can use. Connection's SNI must match
 * one of these for Reality to serve our own handshake (otherwise
 * it proxies to `dest`).
 */
server_names: Array<string>, 
/**
 * base64-url 32-byte x25519 private key. Secret.
 */
private_key: string, 
/**
 * base64-url 32-byte x25519 public key. Embedded in share-links.
 */
public_key: string, 
/**
 * Each entry is 0-16 hex chars (0-8 bytes). Empty string is a
 * valid value meaning "no shortId restriction".
 */
short_ids: Array<string>, 
/**
 * uTLS fingerprint emulation. "chrome" / "firefox" / "ios" etc.
 * Defaults to "chrome" — the safest blanket profile.
 */
fingerprint: string, 
/**
 * PROXY-protocol version (0/1/2). 0 = off.
 */
xver: number, 
/**
 * `SpiderX` — the crawl path the client walks on the real `dest` after
 * an unverified handshake (client-side camouflage against active
 * probing). Emitted to clients as the share-link `spx=` param;
 * xray's server-side Reality config has no spiderX field, so it's
 * share-link-only. Empty defaults to "/". `#[serde(default)]` keeps
 * inbound rows whose stored JSON predates this field deserializing.
 */
spider_x: string, };

export type SecurityConfig = { "kind": "none" } & NoneSecurity | { "kind": "tls" } & TlsSecurity | { "kind": "reality" } & RealitySecurity;

export type SecurityKind = "none" | "tls" | "reality";

export type TlsCertSource = "inline" | "path";

export type TlsCertUsage = "encipherment" | "verify" | "issue";

export type TlsCertificate = { source: TlsCertSource, 
/**
 * PEM blob (Inline) or filesystem path (Path).
 */
cert: string, key: string, usage: TlsCertUsage, ocsp_stapling: number, build_chain: boolean, one_time_loading: boolean, };

export type TlsSecurity = { 
/**
 * At least one entry required when actually using TLS. Empty
 * vector is valid for "configured TLS but not enabled" pre-stage.
 */
certificates: Array<TlsCertificate>, server_name: string | null, 
/**
 * `["h2","http/1.1"]` — order is significant, first wins ALPN
 * negotiation. Default behaviour (None) = `["http/1.1"]` only
 * (WS-compatible).
 */
alpn: Array<string> | null, 
/**
 * "1.2" / "1.3" / "" (xray default = "1.2")
 */
min_version: string | null, max_version: string | null, cipher_suites: string | null, enable_session_resumption: boolean | null, reject_unknown_sni: boolean | null, 
/**
 * NSS-keylog file path. Debug only — exposes session keys.
 */
master_key_log: string | null, 
/**
 * base64-encoded ECH server key bundle (PRIVATE — never leaves
 * the panel except as part of the inbound config xray reads).
 */
ech_server_keys: string | null, 
/**
 * base64-encoded ECH config list (PUBLIC — clients embed this in
 * the TLS Client Hello). Derived from `ech_server_keys` by xray
 * at keygen time. Persisted so the share-link builder can embed
 * it as the `ech=` URL param without re-running keygen.
 */
ech_config_list: string | null, 
/**
 * TLS 1.3 curves list. None = xray default.
 */
curve_preferences: Array<string> | null, 
/**
 * uTLS `ClientHello` fingerprint the client emulates ("chrome",
 * "firefox", "randomized", a version-pinned `hello*`, …). On an inbound
 * this travels in the share-link as `fp=` (the server doesn't emulate);
 * on an OUTBOUND it IS emitted into the TLS proto (`fingerprint`, field
 * 11) so the relay's dialer emulates it. `None`/empty defaults to
 * "chrome".
 */
fingerprint: string | null, 
/**
 * CLIENT-side (outbound relay) only — verify the upstream server's
 * certificate against these names instead of the dial address. The
 * sanctioned replacement for the removed `allowInsecure` when relaying
 * to a server whose cert SAN doesn't match the address it's dialed by.
 * Ignored on inbounds (the server build never reads it).
 */
verify_peer_cert_by_name: Array<string> | null, 
/**
 * CLIENT-side only — pin the upstream's certificate by SHA-256 (hex,
 * optionally colon-separated, or base64). The strict alternative to
 * `verify_peer_cert_by_name`. Ignored on inbounds.
 */
pinned_peer_cert_sha256: Array<string> | null, };
