// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /api/auth/credentials`.
 *
 * `current_password` is always required — proves the caller actually
 * knows the existing password, not just that they hold a still-valid
 * session token (a token can outlive the admin's awareness of it).
 * `new_username` / `new_password` are individually optional so the
 * operator can change either one without re-typing the other; an
 * empty / whitespace-only string is treated the same as "not set".
 * The handler rejects bodies where neither new field carries a value.
 */
export type ChangeCredentialsRequest = { current_password: string, new_username: string | null, new_password: string | null, };

export type LoginRequest = { username: string, password: string, };

export type LoginResponse = { token: string, user: UserView, };

/**
 * Runtime configuration the panel reads from DB at boot. Holds the
 * values an operator can change from the UI without editing the env
 * file: TCP port + URL prefix the panel binds to, plus subscription
 * knobs that shape what `/sub/{token}` returns to client apps. Panel
 * access fields are applied live (port via dual-listener swap, base
 * path via router rebuild); subscription fields are read on every
 * subscription request, so they take effect immediately.
 */
export type PanelSettings = { 
/**
 * Port number; clamped to [1, 65535] at write time.
 */
panel_port: number, 
/**
 * URL prefix the panel mounts under (e.g. `/secret-admin`).
 * Stored with leading slash, no trailing slash; empty string
 * means "mount at root" (the historical behaviour).
 */
panel_base_path: string, 
/**
 * Global kill-switch for `/sub/{token}`. False → every subscription
 * URL 404s (same response as an invalid token, so the surface is
 * indistinguishable from "not configured"). Individual share-links
 * generated from the panel UI keep working.
 */
sub_enabled: boolean, 
/**
 * Optional hostname to substitute for the auto-detected IPv4 / IPv6
 * inside every share-link in the subscription bundle. Empty ≡ keep
 * auto-detect (the panel's outbound IP).
 */
sub_host_override: string, 
/**
 * Hours emitted as `Profile-Update-Interval` so client apps refresh
 * the subscription on their own. Default 12, range [1, 168].
 */
sub_update_interval_hours: number, 
/**
 * Operator-set service name shown in the public subscription
 * landing page header. Empty string ≡ no override → the landing
 * falls back to a neutral generic ("Подписка"). Validation
 * strips control characters and caps at 60 chars.
 */
sub_brand_name: string, 
/**
 * Operator-set URL of the main service (landing, support chat,
 * telegram bot…) shown as a "Перейти на сервис" button in the
 * subscription page header. Empty ≡ button hidden. Validated as
 * `http(s)://...` only, no other schemes.
 */
sub_service_url: string, 
/**
 * Optional dedicated TCP port for the public /sub/{token} endpoint.
 * `0` ≡ disabled (only the main panel port serves subscriptions).
 * Non-zero spins a second axum listener with the admin /api/*
 * routes stripped — useful for putting the public endpoint behind
 * a separate firewall rule / CDN without exposing the admin API.
 */
sub_port: number, };

/**
 * Body for `PUT /api/settings/panel`. Same shape as the read view —
 * kept as a separate type because future writable settings (CORS
 * allowlist, log level, etc.) may carry different validation than
 * the read response.
 */
export type PanelSettingsUpdate = { panel_port: number, panel_base_path: string, sub_enabled: boolean, sub_host_override: string, sub_update_interval_hours: number, sub_brand_name: string, sub_service_url: string, sub_port: number, };

export type UserView = { id: string, username: string, is_admin: boolean, };
