// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /api/auth/credentials`.
 *
 * `current_password` is always required — proves the caller actually
 * knows the existing password, not just that they hold a still-valid
 * session token (a token can outlive the admin's awareness of it).
 * `new_username` / `new_password` are individually optional so the
 * operator can change either one without re-typing the other; an
 * empty / whitespace-only string is treated the same as "not set".
 * The handler rejects bodies where neither new field carries a value.
 */
export type ChangeCredentialsRequest = { current_password: string, new_username: string | null, new_password: string | null, };

export type LoginRequest = { username: string, password: string, };

export type LoginResponse = { token: string, user: UserView, };

/**
 * Runtime configuration the panel reads from DB at boot. Holds the
 * values an operator can change from the UI without editing the env
 * file: TCP port + URL prefix the panel binds to, plus subscription
 * knobs that shape what `/sub/{token}` returns to client apps. Panel
 * access fields are applied live (port via dual-listener swap, base
 * path via router rebuild); subscription fields are read on every
 * subscription request, so they take effect immediately.
 */
export type PanelSettings = { 
/**
 * Port number; clamped to [1, 65535] at write time.
 */
panel_port: number, 
/**
 * URL prefix the panel mounts under (e.g. `/secret-admin`).
 * Stored with leading slash, no trailing slash; empty string
 * means "mount at root" (the historical behaviour).
 */
panel_base_path: string, 
/**
 * Global kill-switch for `/sub/{token}`. False → every subscription
 * URL 404s (same response as an invalid token, so the surface is
 * indistinguishable from "not configured"). Individual share-links
 * generated from the panel UI keep working.
 */
sub_enabled: boolean, 
/**
 * Optional hostname to substitute for the auto-detected IPv4 / IPv6
 * inside every share-link in the subscription bundle — i.e. the server
 * address clients dial. Empty ≡ keep auto-detect (the panel's outbound
 * IP). Distinct from `sub_link_host`, which is the host of the
 * subscription URL itself.
 */
sub_host_override: string, 
/**
 * Optional host for the subscription URL itself (the `/sub/{token}`
 * link the operator shares), independent of `sub_host_override` (the
 * server address baked into the configs). Empty ≡ the panel's own
 * address (the origin the admin opens). Lets the shareable link point
 * at the panel domain while the configs dial a separate tunnel / CDN.
 */
sub_link_host: string, 
/**
 * Hours emitted as `Profile-Update-Interval` so client apps refresh
 * the subscription on their own. Default 12, range [1, 168].
 */
sub_update_interval_hours: number, 
/**
 * Operator-set service name shown in the public subscription
 * landing page header. Empty string ≡ no override → the landing
 * falls back to a neutral generic ("Подписка"). Validation
 * strips control characters and caps at 60 chars.
 */
sub_brand_name: string, 
/**
 * Operator-set URL of the main service (landing, support chat,
 * telegram bot…) shown as a "Перейти на сервис" button in the
 * subscription page header. Empty ≡ button hidden. Validated as
 * `http(s)://...` only, no other schemes.
 */
sub_service_url: string, 
/**
 * Optional dedicated TCP port for the public /sub/{token} endpoint.
 * `0` ≡ disabled (only the main panel port serves subscriptions).
 * Non-zero spins a second axum listener with the admin /api/*
 * routes stripped — useful for putting the public endpoint behind
 * a separate firewall rule / CDN without exposing the admin API.
 */
sub_port: number, 
/**
 * `domainStrategy` of the freedom (`direct`) outbound: `AsIs`,
 * `UseIP*`, or `ForceIP*`. Lives in the bootstrap config, so a
 * change only applies on the next xray restart.
 */
xray_freedom_strategy: string, 
/**
 * `domainStrategy` of the routing block: `AsIs`, `IPIfNonMatch`,
 * or `IPOnDemand`. Same restart-to-apply rule as above.
 */
xray_routing_strategy: string, 
/**
 * URL the "test outbound" button fetches from the server to confirm
 * the egress reaches the internet. Stored only; not part of the xray
 * config (a single freedom outbound needs no observatory).
 */
xray_test_url: string, 
/**
 * Block the sniffed `bittorrent` protocol via a blackhole outbound
 * (needs inbound sniffing enabled to detect it).
 */
xray_block_bittorrent: boolean, 
/**
 * Destinations blackholed. Each entry is a domain, IP/CIDR, or a
 * `geoip:`/`geosite:`/`ext:` matcher xray understands. Stored as a JSON
 * array in the DB; surfaced here as a list.
 */
xray_blocked_ips: Array<string>, xray_blocked_domains: Array<string>, 
/**
 * Domains forced out over IPv4 (routed to a freedom `UseIPv4` outbound).
 */
xray_ipv4_domains: Array<string>, 
/**
 * Operator-defined ordered routing rules, applied after the built-in ones.
 */
xray_custom_rules: Array<RoutingRule>, 
/**
 * Full evaluation order as tokens (system keys + custom rule ids).
 */
xray_rule_order: Array<string>, 
/**
 * Whether the panel serves its own port over HTTPS using an
 * operator-provided cert+key. TLS binds at process start, so a change
 * applies on the next panel restart.
 */
panel_tls_enabled: boolean, 
/**
 * PEM certificate (chain) for the panel HTTPS listener. Public material,
 * round-tripped to the UI so the operator can review and replace it.
 */
panel_tls_cert: string, 
/**
 * Whether a private key is stored. The key itself is never returned to the
 * client — the UI shows a "key configured" state and only transmits a key
 * when the operator pastes a replacement.
 */
panel_tls_key_set: boolean, };

/**
 * Body for `PUT /api/settings/panel`. Same shape as the read view —
 * kept as a separate type because future writable settings (CORS
 * allowlist, log level, etc.) may carry different validation than
 * the read response.
 */
export type PanelSettingsUpdate = { panel_port: number, panel_base_path: string, sub_enabled: boolean, sub_host_override: string, sub_link_host: string, sub_update_interval_hours: number, sub_brand_name: string, sub_service_url: string, sub_port: number, xray_freedom_strategy: string, xray_routing_strategy: string, xray_test_url: string, xray_block_bittorrent: boolean, xray_blocked_ips: Array<string>, xray_blocked_domains: Array<string>, xray_ipv4_domains: Array<string>, xray_custom_rules: Array<RoutingRule>, xray_rule_order: Array<string>, panel_tls_enabled: boolean, panel_tls_cert: string, 
/**
 * New private key (PEM). Empty string ≡ keep the stored key — so saving any
 * other settings section doesn't wipe it and the key need only be pasted
 * once. A non-empty value replaces the stored key.
 */
panel_tls_key: string, };

/**
 * One operator-defined routing rule. Stored (by id) in `xray_custom_rules`;
 * its position in the evaluation order is held separately in
 * `xray_rule_order`. All matchers are AND-ed; an empty matcher is omitted.
 * v1 target is a single `outbound_tag` (direct / blocked / direct-ipv4).
 */
export type RoutingRule = { id: string, enabled: boolean, 
/**
 * Panel-only label; not emitted to xray.
 */
name: string, domain: Array<string>, ip: Array<string>, source_ip: Array<string>, port: string, source_port: string, network: Array<string>, protocol: Array<string>, inbound_tag: Array<string>, user: Array<string>, outbound_tag: string, };

export type UserView = { id: string, username: string, is_admin: boolean, };
