// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DashboardOverview = { system: SystemStats, xray: XrayStatus, inbounds_total: number, inbounds_enabled: number, };

export type LogEntry = { 
/**
 * ISO-8601 UTC timestamp.
 */
timestamp: string, 
/**
 * `trace` | `debug` | `info` | `warn` | `error`.
 */
level: string, 
/**
 * Originating module path (e.g. `<crate>::xray::reload`).
 */
target: string, 
/**
 * Rendered message text.
 */
message: string, };

export type SystemStats = { cpu_percent: number, cpu_cores: number, memory_used_bytes: number, memory_total_bytes: number, disk_used_bytes: number, disk_total_bytes: number, swap_used_bytes: number, swap_total_bytes: number, uptime_seconds: number, 
/**
 * Outbound-facing IPv4 of the host (the address a packet to the public
 * internet would leave on). `None` if there is no v4 route at all.
 */
ipv4: string | null, 
/**
 * Same for IPv6. `None` when the host has no global v6.
 */
ipv6: string | null, };

/**
 * One client's live counters, exposed as-is to the frontend.
 */
export type TrafficSnapshot = { 
/**
 * `true` if xray reports at least one active TCP connection OR
 * the user moved any bytes during the last poll interval. The
 * `bps > 0` fallback catches short-lived HTTP-style traffic
 * where every request opens and closes a socket inside one
 * poll window — `GetAllOnlineUsers` alone never sees those
 * sockets and would flag the user offline despite obvious
 * activity.
 */
online: boolean, 
/**
 * Lifetime uplink bytes (user→outbound). Includes everything the
 * panel has ever seen for this email across xray + backend
 * restarts; backed by the `clients.uplink_total` column.
 */
uplink_total: number, 
/**
 * Lifetime downlink bytes (outbound→user). Same persistence
 * semantics as `uplink_total`.
 */
downlink_total: number, 
/**
 * Bytes/sec rate over the last poll interval (uplink). 0 on the
 * first tick after backend start or after an xray restart.
 */
uplink_bps: number, 
/**
 * Bytes/sec rate over the last poll interval (downlink).
 */
downlink_bps: number, };

/**
 * One row in the "Обновления Xray" modal — what the UI needs per version.
 */
export type XrayRelease = { tag: string, published_at: string, prerelease: boolean, 
/**
 * Direct download URL of the asset matching the host platform, if any.
 * `None` means this release has no build for the current OS/arch.
 */
asset_url: string | null, asset_size: number | null, };

export type XrayStatus = { running: boolean, pid: number | null, version: string | null, started_at: string | null, };
