// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HysteriaMasquerade = { "kind": "notfound" } | { "kind": "file", root: string, } | { "kind": "proxy", url: string, rewrite_host: boolean, insecure: boolean, } | { "kind": "string", content: string, headers: { [key in string]: string }, status_code: number, };

export type HysteriaTransport = { 
/**
 * Server-wide auth fallback. Used only when `users[]` is empty on
 * the protocol side; the panel prefers per-user auth (Client.auth)
 * and leaves this empty.
 */
auth: string | null, 
/**
 * UDP session idle timeout in seconds. `None` ≡ upstream default (60s).
 */
udp_idle_timeout: number | null, masquerade: HysteriaMasquerade, 
/**
 * Stream-level QUIC tuning. xray reads this off
 * `StreamConfig.quic_params`, not the hysteria proto itself, so
 * the orchestrator routes it via the shared `Transport::quic_params_proto`
 * trait method. `None` leaves all QUIC knobs at xray defaults.
 */
quic_params: QuicParams | null, };

/**
 * Congestion-control algorithm. xray's hysteria hub maps these
 * strings 1:1 — see `hub.go` switch over `quicParams.Congestion`.
 */
export type QuicCongestion = "reno" | "bbr" | "brutal" | "force-brutal";

export type QuicParams = { congestion: QuicCongestion | null, 
/**
 * BBR sub-profile (e.g. "standard", "fastpath"). Only consulted
 * when `congestion == Bbr` or Brutal-fallback hits BBR.
 */
bbr_profile: string | null, 
/**
 * Brutal-mode upstream cap, **megabits/sec** in xray's wire
 * format. Required when `congestion == Brutal` for the cap to
 * have effect (else falls back to BBR).
 */
brutal_up_mbps: number | null, 
/**
 * Brutal-mode downstream cap, megabits/sec.
 */
brutal_down_mbps: number | null, udp_hop: UdpHop | null, 
/**
 * Initial QUIC stream receive window, in bytes.
 */
init_stream_receive_window: number | null, max_stream_receive_window: number | null, init_conn_receive_window: number | null, max_conn_receive_window: number | null, 
/**
 * Connection idle timeout, seconds. 0 / `None` ≡ xray default.
 */
max_idle_timeout_secs: number | null, 
/**
 * QUIC keepalive period, seconds. 0 disables.
 */
keep_alive_period_secs: number | null, 
/**
 * Skip the QUIC Path MTU discovery probe. Set for misbehaving
 * middleboxes that drop the probe packets.
 */
disable_path_mtu_discovery: boolean, 
/**
 * Max concurrent inbound streams per connection. 0 ≡ default.
 */
max_incoming_streams: number | null, };

export type TcpTransport = Record<symbol, never>;

/**
 * Tagged-union of every transport variant. Lives on `Inbound` as the
 * `transport` field and serializes to a single JSON blob in the DB.
 * `#[serde(tag = "kind")]` produces `{"kind": "ws", "path": "/"}` —
 * matches what TypeScript's discriminated union expects.
 *
 * `Xhttp` is ~640 B vs ~104 B for `Ws` and ~16 B for `Tcp`, which
 * clippy flags as `large_enum_variant`. Boxing the big variant would
 * trade an extra heap allocation per inbound for a smaller stack
 * footprint and risk a ts-rs serialization surprise (Box transparency
 * isn't guaranteed across versions). The panel holds at most a
 * double-digit number of inbounds in memory, so the stack-size win
 * isn't worth either cost — silence the lint with an explicit rationale.
 */
export type TransportConfig = { "kind": "tcp" } & TcpTransport | { "kind": "ws" } & WsTransport | { "kind": "xhttp" } & XhttpTransport | { "kind": "hysteria" } & HysteriaTransport;

/**
 * Discriminator used in the persisted JSON blob (`inbounds.transport_config`)
 * and on the wire to identify which variant of `TransportConfig` follows.
 */
export type TransportKind = "tcp" | "ws" | "xhttp" | "hysteria";

/**
 * UDP port-hopping — defeats simple port-based blocking by rotating
 * the listening port from the `ports` set every `interval_min..max`
 * seconds.
 */
export type UdpHop = { 
/**
 * Ports to rotate through. Must contain at least one entry.
 */
ports: Array<number>, 
/**
 * Lower bound of the random hop interval, in seconds.
 */
interval_min: number, 
/**
 * Upper bound. `min == max` produces a fixed cadence.
 */
interval_max: number, };

export type WsTransport = { 
/**
 * URL path for the WS upgrade handshake. Defaults to "/". Behind a
 * CDN this is the route the CDN forwards on.
 */
path: string | null, 
/**
 * Override for the upstream Host header. Empty = use whatever the
 * client sent. Used when CDN's incoming host differs from xray's
 * expected vhost.
 */
host: string | null, 
/**
 * Custom HTTP headers. `BTreeMap` for stable JSON serialization in
 * the panel's persisted blob; converted to `HashMap` when feeding
 * the prost-generated proto.
 */
headers: { [key in string]: string } | null, 
/**
 * PROXY-protocol acceptance. When `true`, expects the front-end
 * (nginx/HAProxy) to prepend PROXY headers so xray can see the
 * real client IP.
 */
accept_proxy_protocol: boolean | null, 
/**
 * WS Ping interval in seconds. `0` (or `None`) = disabled. Useful
 * behind CDNs that kill idle connections after N seconds.
 */
heartbeat_period: number | null, };

/**
 * XHTTP mode — see xray-core `infra/conf/transport_internet.go::SplitHTTPConfig.Build`.
 */
export type XhttpMode = "auto" | "packet-up" | "stream-up" | "stream-one";

export type XhttpTransport = { path: string | null, host: string | null, mode: XhttpMode | null, headers: { [key in string]: string } | null, x_padding_bytes: string | null, no_grpc_header: boolean | null, no_sse_header: boolean | null, sc_max_each_post_bytes: string | null, sc_min_posts_interval_ms: string | null, sc_max_buffered_posts: number | null, sc_stream_up_server_secs: string | null, xmux_max_concurrency: string | null, xmux_max_connections: string | null, xmux_c_max_reuse_times: string | null, xmux_h_max_request_times: string | null, xmux_h_max_reusable_secs: string | null, xmux_h_keep_alive_period: number | null, x_padding_obfs_mode: boolean | null, x_padding_key: string | null, x_padding_header: string | null, x_padding_placement: string | null, x_padding_method: string | null, uplink_http_method: string | null, session_id_placement: string | null, session_id_key: string | null, 
/**
 * Predefined table name (ALPHABET/Alphabet/BASE36/Base62/HEX/alphabet/
 * base36/hex/number) or a custom ASCII alphabet for the session ID.
 */
session_id_table: string | null, 
/**
 * Session-ID length range ("8" or "8-16"). Empty ≡ xray default.
 */
session_id_length: string | null, seq_placement: string | null, seq_key: string | null, uplink_data_placement: string | null, uplink_data_key: string | null, uplink_chunk_size: string | null, server_max_header_bytes: number | null, 
/**
 * Stream-level QUIC tuning. xray's splithttp reads this off
 * `StreamConfig.quic_params` when running in H3 mode
 * (`ALPN=["h3"]`); ignored for the TCP / H2 modes. Routed
 * through `Transport::quic_params_proto`.
 */
quic_params: QuicParams | null, };
